version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: sudais/finals
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t su:sudais .
      - run:
          name: Login Dockerhub
          command: docker login -u sudaiss -p sudais22
      - run:
          name: Push Docker Image
          command: docker push sudais22/su
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
