version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: sudais/finals
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t sudaiss/final:final .
      - run:
          name: Login Dockerhub
          command: docker login -u sudaiss -p sudais22
      - run:
          name: Push Docker Image
          command: docker push sudaiss/final:final

workflows:
  version: 2
  
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  my-workflow:
    jobs:
      - run-tests:
          context: sudais          
